import type { Metadata } from "next";
import { Sawarabi_Gothic } from 'next/font/google';
import Header from "@/components/layout/Header";
import "@/styles/globals.css";

const font = Sawarabi_Gothic({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="jp-ja">
      <body className={`antialiased ${font.className}`} >
        <div className="p-3">
          <Header />
        </div>
        
        { children }
      </body>
    </html>
  );
}
